#line_file_path: "/home/ubuntu/Desktop/BPC-PRP/resources/route_1.yaml"
#line_file_path: "/home/ubuntu/Desktop/GIT/projekt_linefollower/map_gen_maps/zatacky.yaml"
line_file_path: "/home/ricky/projekt_linefollower/map_gen_maps/zatacky_vic_basic_orezana.yaml"

#line_file_path: "/home/default_user/Developer/bpc-prp-project/resources/route_2.yaml"
#line_file_path: "/home/default_user/Developer/bpc-prp-project/resources/route_3.yaml"

simulation:
  port_in: 8080
  port_out: 8081
  verbose: false
  simulation_period: 0.005
  visualization_period: 0.01

robot:
  pose:
    x: 0.0
    y: 0.0
  orientation_deg: 270.0

  wheel_radius: 0.035
  chassis_base: 0.12

  width: 0.1
  length: 0.1
  height: 0.1

  body_offset:
    x: 0.0
    y: 0.0
    z: 0.01

  line_sensors:
  - [ 0.05, -0.035, 0.01]
  - [ 0.05,  0.00, 0.01 ]
  - [ 0.05,  0.025, 0.01 ]
